#logging:
#    level:
#        org.springframework.data.document.mongodb: DEBUG
#        org.springframework.security: DEBUG
log4j:
    category:
        org.springframework.data.document.mongodb: DEBUG
security:
    oauth2:
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
spring:
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat