logging:
    level:
        org.springframework.security: DEBUG
security:
    oauth2:
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false